// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.springbook.myapp.mydata;

import jp.springbook.myapp.mydata.MyDataIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MyDataIntegrationTest_Roo_Configurable {
    
    declare @type: MyDataIntegrationTest: @Configurable;
    
}
